apiVersion: apps/v1
kind: Deployment
metadata:
   name: be-service-registry-deployment
   labels:
      type: service-registry-deployment
      app: backend-sr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: service-registry
  template:
    metadata:
      name: service-registry-pod
      labels:
        type: service-registry
    spec:
      containers:
      - name: bc125-backend-service-registry
        image: ghcr.io/paritosh-pranjal/bc125-be-eks-service-registry:v4
        ports:
        - containerPort: 8761
      imagePullSecrets: 
      - name: ghcr-secret
